model_name: tinyllama
model_path: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
tokenizer_path: TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T
attn_implementation: eager  # align with CBD-CKPT for fair comparison
